Add shellcheck and shfmt
plus address all shellcheck gripes

diff --git a/gimme b/gimme
--- a/gimme
+++ b/gimme
@@ -49,22 +49,23 @@ set -o pipefail
 GIMME_VERSION="v1.0.0-9-g97889f2"
 GIMME_COPYRIGHT="Copyright (c) 2016 Dan Buch, Tianon Gravi, Travis CI GmbH"
 GIMME_LICENSE_URL="https://raw.githubusercontent.com/travis-ci/gimme/97889f2/LICENSE"
+export GIMME_LICENSE_URL GIMME_COPYRIGHT
 
 # _do_curl "url" "file"
 _do_curl() {
 	mkdir -p "$(dirname "${2}")"
 
-	if command -v curl > /dev/null ; then
+	if command -v curl >/dev/null; then
 		curl -sSLf "${1}" -o "${2}" 2>/dev/null
 		return
 	fi
 
-	if command -v wget > /dev/null ; then
+	if command -v wget >/dev/null; then
 		wget -q "${1}" -O "${2}" 2>/dev/null
 		return
 	fi
 
-	if command -v fetch > /dev/null ; then
+	if command -v fetch >/dev/null; then
 		fetch -q "${1}" -o "${2}" 2>/dev/null
 		return
 	fi
@@ -78,8 +79,8 @@ _do_curls() {
 	f="${1}"
 	shift
 	[[ ! -s "${f}" ]] || return 0
-	for url in "${@}" ; do
-		if _do_curl "${url}" "${f}" ; then
+	for url in "${@}"; do
+		if _do_curl "${url}" "${f}"; then
 			return
 		fi
 	done
@@ -95,21 +96,21 @@ _binary() {
 	urls=(
 		"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}.tar.gz"
 	)
-	if [ "${GIMME_OS}" = 'darwin' -a "${GIMME_BINARY_OSX}" ] ; then
+	if [ "${GIMME_OS}" = 'darwin' ] && [ -n "${GIMME_BINARY_OSX}" ]; then
 		urls=(
 			"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}-${GIMME_BINARY_OSX}.tar.gz"
 			"${urls[@]}"
 		)
 	fi
-	if [ "${arch}" = 'arm' ] ; then
+	if [ "${arch}" = 'arm' ]; then
 		# attempt "armv6l" vs just "arm" first (since that's what's officially published)
 		urls=(
-			"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}v6l.tar.gz" # go1.6beta2 & go1.6rc1
-			"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}6.tar.gz" # go1.6beta1
-			"${urls[@]}"
+			"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}v6l.tar.gz"
+			"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}6.tar.gz"
+			"${urls[@]}" # go1.6beta2 & go1.6rc1 # go1.6beta1
 		)
 	fi
-	if [ "${GIMME_OS}" = 'windows' ] ; then
+	if [ "${GIMME_OS}" = 'windows' ]; then
 		urls=(
 			"${GIMME_DOWNLOAD_BASE}/go${version}.${GIMME_OS}-${arch}.zip"
 		)
@@ -130,7 +131,7 @@ _source() {
 _fetch() {
 	mkdir -p "$(dirname "${1}")"
 
-	if [[ -d "${1}/.git" ]] ; then
+	if [[ -d "${1}/.git" ]]; then
 		(
 			cd "${1}"
 			git remote set-url origin "${GIMME_GO_GIT_REMOTE}"
@@ -145,20 +146,20 @@ _fetch() {
 # _checkout "version" "dir"
 _checkout() {
 	_fetch "${2}"
-	( cd "${2}" && {
+	(cd "${2}" && {
 		git reset -q --hard "origin/${1}" \
-		|| git reset -q --hard "origin/go${1}" \
-		|| { [ "${1}" = 'tip' ] && git reset -q --hard origin/master ; } \
-		|| git reset -q --hard "refs/tags/${1}" \
-		|| git reset -q --hard "refs/tags/go${1}"
-	} 2>/dev/null )
+			|| git reset -q --hard "origin/go${1}" \
+			|| { [ "${1}" = 'tip' ] && git reset -q --hard origin/master; } \
+				|| git reset -q --hard "refs/tags/${1}" \
+				|| git reset -q --hard "refs/tags/go${1}"
+	} 2>/dev/null)
 }
 
 # _extract "file.tar.gz" "dir"
 _extract() {
 	mkdir -p "${2}"
 
-	if [[ "${1}" == *.tar.gz ]] ; then
+	if [[ "${1}" == *.tar.gz ]]; then
 		tar -xf "${1}" -C "${2}" --strip-components 1
 	else
 		unzip -q "${1}" -d "${2}"
@@ -172,35 +173,37 @@ _setup_bootstrap() {
 	local versions=("1.6" "1.5" "1.4")
 
 	# try existing
-	for v in "${versions[@]}" ; do
-		for candidate in "${GIMME_ENV_PREFIX}/go${v}"*".env" ; do
+	for v in "${versions[@]}"; do
+		for candidate in "${GIMME_ENV_PREFIX}/go${v}"*".env"; do
 			if [ -s "$candidate" ]; then
-				export GOROOT_BOOTSTRAP="$(source "${candidate}" 2>/dev/null && go env GOROOT)"
+				# shellcheck source=/dev/null
+				GOROOT_BOOTSTRAP="$(source "${candidate}" 2>/dev/null && go env GOROOT)"
+				export GOROOT_BOOTSTRAP
 				return 0
 			fi
 		done
 	done
 
 	# try binary
-	for v in "${versions[@]}" ; do
-		if [ -n  "$(_try_binary ${v} "${GIMME_HOSTARCH}")" ]; then
+	for v in "${versions[@]}"; do
+		if [ -n "$(_try_binary "${v}" "${GIMME_HOSTARCH}")" ]; then
 			export GOROOT_BOOTSTRAP="${GIMME_VERSION_PREFIX}/go${v}.${GIMME_OS}.${GIMME_HOSTARCH}"
 			return 0
 		fi
 	done
 
-	echo >&2 "Unable to setup go bootstrap from existing or binary";
-	return 1;
+	echo >&2 "Unable to setup go bootstrap from existing or binary"
+	return 1
 }
 
 # _compile "dir"
 _compile() {
 	(
-		if grep -q GOROOT_BOOTSTRAP "${1}/src/make.bash" &> /dev/null; then
+		if grep -q GOROOT_BOOTSTRAP "${1}/src/make.bash" &>/dev/null; then
 			_setup_bootstrap || return 1
 		fi
 		cd "${1}"
-		if [[ -d .git ]] ; then
+		if [[ -d .git ]]; then
 			git clean -dfx -q
 		fi
 		cd src
@@ -209,16 +212,16 @@ _compile() {
 		export CC_FOR_TARGET="${GIMME_CC_FOR_TARGET}"
 
 		local make_log="${1}/make.${GOOS}.${GOARCH}.log"
-		if [ "${GIMME_DEBUG}" > "1" ]; then
-			./make.bash 2>&1 | tee $make_log 1>&2 || return 1
+		if [ "${GIMME_DEBUG}" ] >"1"; then
+			./make.bash 2>&1 | tee "${make_log}" 1>&2 || return 1
 		else
-			./make.bash &> $make_log || return 1
+			./make.bash &>"${make_log}" || return 1
 		fi
 	)
 }
 
 _can_compile() {
-	cat > "${GIMME_TMP}/test.go" <<'EOF'
+	cat >"${GIMME_TMP}/test.go" <<'EOF'
 package main
 import "os"
 func main() {
@@ -230,34 +233,34 @@ EOF
 
 # _env "dir"
 _env() {
-	[ -d "${1}/bin" -a -x "${1}/bin/go" ] || return 1
+	([ -d "${1}/bin" ] && [ -x "${1}/bin/go" ]) || return 1
 
 	# if we try to run a Darwin binary on Linux, we need to fail so 'auto' can fallback to cross-compiling from source
 	# automatically
-	GOROOT="${1}" "${1}/bin/go" version &> /dev/null || return 1
+	GOROOT="${1}" "${1}/bin/go" version &>/dev/null || return 1
 
 	# https://twitter.com/davecheney/status/431581286918934528
 	# we have to GOROOT sometimes because we use official release binaries in unofficial locations :(
 
 	echo
-	if [[ "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTOS)" = "${GIMME_OS}" ]] ; then
+	if [[ "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTOS)" = "${GIMME_OS}" ]]; then
 		echo 'unset GOOS'
 	else
 		echo 'export GOOS="'"${GIMME_OS}"'"'
 	fi
-	if [[ "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTARCH)" = "${GIMME_ARCH}" ]] ; then
+	if [[ "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTARCH)" = "${GIMME_ARCH}" ]]; then
 		echo 'unset GOARCH'
 	else
 		echo 'export GOARCH="'"${GIMME_ARCH}"'"'
 	fi
-	if ! _can_compile "${1}" >/dev/null 2>&1 ; then
+	if ! _can_compile "${1}" >/dev/null 2>&1; then
 		# if the compile test fails without GOROOT, then we probably need GOROOT
 		echo 'export GOROOT="'"${1}"'"'
 	else
 		echo 'unset GOROOT'
 	fi
-	echo 'export PATH="'"${1}/bin"':${PATH}"'
-	if [[ -z "${GIMME_SILENT_ENV}" ]] ; then
+	echo "export PATH=\"${1}/bini\":${PATH}"
+	if [[ -z "${GIMME_SILENT_ENV}" ]]; then
 		echo 'go version >&2'
 	fi
 	echo
@@ -265,13 +268,13 @@ _env() {
 
 # _env_alias "dir" "env-file"
 _env_alias() {
-	if [[ "${GIMME_NO_ENV_ALIAS}" ]] ; then
+	if [[ "${GIMME_NO_ENV_ALIAS}" ]]; then
 		echo "${2}"
 		return
 	fi
 
-	if [[ "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTOS)" = "${GIMME_OS}"  && \
-		"$(GOROOT="${1}" "${1}/bin/go" env GOHOSTARCH)" = "${GIMME_ARCH}" ]] ; then
+	if [[ "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTOS)" = "${GIMME_OS}" \
+		&& "$(GOROOT="${1}" "${1}/bin/go" env GOHOSTARCH)" = "${GIMME_ARCH}" ]]; then
 		local dest="${GIMME_ENV_PREFIX}/go${GIMME_GO_VERSION}.env"
 		cp "${2}" "${dest}"
 		ln -sf "${dest}" "${GIMME_ENV_PREFIX}/latest.env"
@@ -285,7 +288,7 @@ _try_existing() {
 	local existing_ver="${GIMME_VERSION_PREFIX}/go${GIMME_GO_VERSION}.${GIMME_OS}.${GIMME_ARCH}"
 	local existing_env="${GIMME_ENV_PREFIX}/go${GIMME_GO_VERSION}.${GIMME_OS}.${GIMME_ARCH}.env"
 
-	if [[ -x "${existing_ver}/bin/go" &&  -s "${existing_env}" ]] ; then
+	if [[ -x "${existing_ver}/bin/go" && -s "${existing_env}" ]]; then
 		cat "${existing_env}"
 		return
 	fi
@@ -301,7 +304,7 @@ _try_binary() {
 	local bin_dir="${GIMME_VERSION_PREFIX}/go${version}.${GIMME_OS}.${arch}"
 	local bin_env="${GIMME_ENV_PREFIX}/go${version}.${GIMME_OS}.${arch}.env"
 
-	if [ "${GIMME_OS}" = 'windows' ] ; then
+	if [ "${GIMME_OS}" = 'windows' ]; then
 		bin_tgz=${bin_tgz%.tar.gz}.zip
 	fi
 
@@ -336,62 +339,63 @@ _try_git() {
 _wipe_version() {
 	local env_file="${GIMME_ENV_PREFIX}/go${1}.${GIMME_OS}.${GIMME_ARCH}.env"
 
-	if [[ -s "${env_file}" ]] ; then
+	if [[ -s "${env_file}" ]]; then
 		rm -rf "$(awk -F\" '/GOROOT/ { print $2 }' "${env_file}")"
 		rm -f "${env_file}"
 	fi
 }
 
 _list_versions() {
-	if [ ! -d "${GIMME_VERSION_PREFIX}" ] ; then
+	if [ ! -d "${GIMME_VERSION_PREFIX}" ]; then
 		return 0
 	fi
 
-	local current_version="$(go env GOROOT 2>/dev/null)"
+	local current_version
+	current_version="$(go env GOROOT 2>/dev/null)"
 	current_version="${current_version##*/go}"
 	current_version="${current_version%%.${GIMME_OS}.*}"
 
-	for d in "${GIMME_VERSION_PREFIX}/go"*".${GIMME_OS}."* ; do
+	for d in "${GIMME_VERSION_PREFIX}/go"*".${GIMME_OS}."*; do
 		local cleaned="${d##*/go}"
 		cleaned="${cleaned%%.${GIMME_OS}.*}"
 		echo -en "${cleaned}"
-		if [[ $cleaned = $current_version ]] ; then
-			echo -en >&2 ' <= current'
+		if [[ "${cleaned}" = "${current_version}" ]]; then
+			echo -en ' <= current' >&2
 		fi
 		echo
 	done
 }
 
 _realpath() {
-	[ -d "$1" ] && echo "$(cd "$1" && pwd)" || echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
+	[ -d "$1" ] && (cd "$1" && pwd) || echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
 }
 
 _assert_version_given() {
-	if [[ -z "${GIMME_GO_VERSION}" ]] ; then
+	if [[ -z "${GIMME_GO_VERSION}" ]]; then
 		echo >&2 'error: no GIMME_GO_VERSION supplied'
-		echo >&2 "  ex: GIMME_GO_VERSION=1.4.1 ${0} ${@}"
-		echo >&2 "  ex: ${0} 1.4.1 ${@}"
+		echo >&2 "  ex: GIMME_GO_VERSION=1.4.1 ${0} ${*}"
+		echo >&2 "  ex: ${0} 1.4.1 ${*}"
 		exit 1
 	fi
 }
 
-: ${GIMME_OS:=$(uname -s | tr '[:upper:]' '[:lower:]')}
-: ${GIMME_HOSTOS:=$(uname -s | tr '[:upper:]' '[:lower:]')}
-: ${GIMME_ARCH:=$(uname -m)}
-: ${GIMME_HOSTARCH:=$(uname -m)}
-: ${GIMME_ENV_PREFIX:=${HOME}/.gimme/envs}
-: ${GIMME_VERSION_PREFIX:=${HOME}/.gimme/versions}
-: ${GIMME_TMP:=${TMPDIR:-/tmp}/gimme}
-: ${GIMME_GO_GIT_REMOTE:=https://github.com/golang/go.git}
-: ${GIMME_TYPE:=auto} # 'auto', 'binary', 'source', or 'git'
-: ${GIMME_BINARY_OSX:=osx10.8}
+: "${GIMME_OS:=$(uname -s | tr '[:upper:]' '[:lower:]')}"
+: "${GIMME_HOSTOS:=$(uname -s | tr '[:upper:]' '[:lower:]')}"
+: "${GIMME_ARCH:=$(uname -m)}"
+: "${GIMME_HOSTARCH:=$(uname -m)}"
+: "${GIMME_ENV_PREFIX:=${HOME}/.gimme/envs}"
+: "${GIMME_VERSION_PREFIX:=${HOME}/.gimme/versions}"
+: "${GIMME_TMP:=${TMPDIR:-/tmp}/gimme}"
+: "${GIMME_GO_GIT_REMOTE:=https://github.com/golang/go.git}"
+: "${GIMME_TYPE:=auto}" # 'auto', 'binary', 'source', or 'git'
+: "${GIMME_BINARY_OSX:=osx10.8}"
 : "${GIMME_DOWNLOAD_BASE:=https://storage.googleapis.com/golang}"
 
-if [[ "${GIMME_OS}" == mingw* ]] ; then
+if [[ "${GIMME_OS}" == mingw* ]]; then
 	# Minimalist GNU for Windows
 	GIMME_OS='windows'
 
-	if [ "${GIMME_ARCH}" = 'i686' ] ; then
+	if [ "${GIMME_ARCH}" = 'i686' ]; then
 		GIMME_ARCH="386"
 	else
 		GIMME_ARCH="amd64"
@@ -400,41 +404,42 @@ fi
 
 while [[ $# -gt 0 ]]; do
 	case "${1}" in
-		-h|--help|help|wat)
+		-h | --help | help | wat)
 			_old_ifs="$IFS"
 			IFS=';'
 			awk '/^#\+  / {
 				sub(/^#\+  /, "", $0) ;
 				sub(/-$/, "", $0) ;
 				print $0
-			}' "$0" | while read line ; do
-				eval "echo \"$line\""
-			done
+			}' \
+				"$0" | while read -r line; do
+					eval "echo \"$line\""
+				done
 			IFS="$_old_ifs"
 			exit 0
-		;;
-		-V|--version|version)
+			;;
+		-V | --version | version)
 			echo "${GIMME_VERSION}"
 			exit 0
-		;;
-		-l|--list|list)
+			;;
+		-l | --list | list)
 			_list_versions
 			exit 0
-		;;
-		-f|--force|force)
+			;;
+		-f | --force | force)
 			force=1
-		;;
+			;;
 		*)
 			break
-		;;
+			;;
 	esac
 	shift
 done
 
-if [[ -n "${1}" ]] ; then
+if [[ -n "${1}" ]]; then
 	GIMME_GO_VERSION="${1}"
 fi
-if [[ -n "${2}" ]] ; then
+if [[ -n "${2}" ]]; then
 	GIMME_VERSION_PREFIX="${2}"
 fi
 
@@ -442,15 +447,15 @@ case "${GIMME_ARCH}" in
 	x86_64) GIMME_ARCH=amd64 ;;
 	x86) GIMME_ARCH=386 ;;
 	arm64)
-		if [[ "${GIMME_GO_VERSION}" < "1.5" ]]; then
+		if [[ "${GIMME_GO_VERSION}" ]] <"1.5"; then
 			echo >&2 "error: ${GIMME_ARCH} is not supported by this go version"
 			echo >&2 "try go1.5 or newer"
 			exit 1
 		fi
 		if [[ "${GIMME_HOSTOS}" = "linux" && "${GIMME_HOSTARCH}" != "${GIMME_ARCH}" ]]; then
-			: ${GIMME_CC_FOR_TARGET:="aarch64-linux-gnu-gcc"}
+			: "${GIMME_CC_FOR_TARGET:="aarch64-linux-gnu-gcc"}"
 		fi
-	;;
+		;;
 	arm*) GIMME_ARCH=arm ;;
 esac
 
@@ -481,14 +486,14 @@ GIMME_ENV_PREFIX="$(_realpath "${GIMME_ENV_PREFIX}")"
 if ! case "${GIMME_TYPE}" in
 	binary) _try_existing || _try_binary "${GIMME_GO_VERSION}" "${GIMME_ARCH}" ;;
 	source) _try_source || _try_git ;;
-	git)    _try_git ;;
-	auto)   _try_existing || _try_binary  "${GIMME_GO_VERSION}" "${GIMME_ARCH}" || _try_source || _try_git ;;
+	git) _try_git ;;
+	auto) _try_existing || _try_binary "${GIMME_GO_VERSION}" "${GIMME_ARCH}" || _try_source || _try_git ;;
 	*)
 		echo >&2 "I don't know how to '${GIMME_TYPE}'."
 		echo >&2 "  Try 'auto', 'binary', 'source', or 'git'."
 		exit 1
 		;;
-esac ; then
+esac; then
 	echo >&2 "I don't have any idea what to do with '${GIMME_GO_VERSION}'."
 	echo >&2 "  (using type '${GIMME_TYPE}')"
 	exit 1
